languageCode = "en"
languageName = "English"
weight = 1
title = "SFI EFLU"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/sfieflu2.jpg"
  #secondaryLogo = "img/sfieflu2.jpg"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "SFI EFLU"
   image = "img/sfieflu2.jpg"
   headline = "Study and Struggle"
   bio = "Philosophers thus far have only interpreted the world in various ways, the point, however, is to change it"
   links = [
     { email = "mailto:sfi.eflu@gmail.com" },
     { instagram = "https://instagram.com/sfieflu" },
     { whatsapp = "https://chat.whatsapp.com/Da9vgW85p2CHRmxfYSxkup" },
   ]
